dist: bionic
language: python

python:
  - "3.7"

addons:
  apt:
    packages:
      - gir1.2-gst-plugins-base-1.0
      - gir1.2-gstreamer-1.0
      - python3-gst-1.0

install:
  - pip install tox

script:
  - tox -r

